### ISSUE TITLE
Transaction fee rework

### ISSUE THREAD

**Issue by sulmone** [z-classic/electrum-zcl#10]
Currently the gui uses a bitcoin centric dynamic fee calculation (with a manual option hidden away).  Remove this and replace it with a flat but adjustable default value.

**Comment by ch4ot1c** [comment]
Done & Merged:

https://github.com/BTCP-community/electrum-zcl/commit/92670af0c81ed61a5fa5506f0327a540fef9e254
https://github.com/BTCP-community/electrum-zcl/commit/b0a28cf5ca3b49f954a368085ae3bef9e7510103
