### ISSUE TITLE
Electrum Wallet not sending ZCl

### ISSUE THREAD

**Issue by izzytoshi** [z-classic/electrum-zcl#101]
Hello,

My wallet is not sending ZCL to another ZCL address.  When I hit send nothing happens.  I currently am running version 1.0.3 and am using the latest surface laptop.  I was able to transfer from my Bittrex account but I am trying to donate to friends to promote ZCl but nothing happens when I hit send.  Please Help

Thank you

**Comment by Alno1964** [comment]
Hi, same problem here, not able to send ZCL (nothing happens) , imported them from Bittrex without any problems but completely stuck now.  Version 1.0.0.  Is there a way to get my Zcl's out of the wallet ?  Thx

**Comment by tinkermade** [comment]
Hi, same problem here.  Running Z!1.0.0. on Windows 10 Education version 1703, OS build 15063.909.  I have tried to send .01 ZCL, .1 ZCL, and 1 ZCL to a Bittrex wallet but the Preview and Send buttons are unresponsive.  The Clear button works correctly, however.  Is there documentation available for best practices for upgrading wallet versions?  Thank you!

**Comment by danrempel** [comment]
@izzytoshi @Alno1964 @tinkermade It likely means you guys created a 2fa wallet despite the ReadMe of 1.0.0 stating "Please do not use wallet type '2FA' yet". I made the same mistake but luckily I only tested the wallet out with a small amount. I've heard there's a workaround to get your money out of the wallet but I haven't found it yet. Hoping one of the dev's post the solution in here before the fork.

**Comment by danrempel** [comment]
@izzytoshi @Alno1964 @tinkermade Actually I just found the dev's solution in a different issue: https://github.com/BTCP-community/electrum-zcl/issues/44

**Comment by tinkermade** [comment]
Thanks for the info. I found the work around here:
https://www.reddit.com/r/ZClassic/comments/7u82rx/2fa_removed_in_electrum_wallet_102_does_this/

"The 2FA does not work but you can recover your balance Guide to Recover ZCL from a 2FA Electrum Wallet – Windows

Have you accidently set up your wallet as a 2FA wallet and now are unable to send coins else where? Has sweeping/ importing your private key not worked for you? As long as you sent the coins as a Transparent (T) address, this is the guide for you! If you used a Private (Z) address, follow up to step 4 and hang tight for when we release Electrum support for Private (Z) addresses.

Create a new standard wallet and restore the 2FA wallet using your “seed” codes. DO NOT password protect this wallet.
Disable the 2FA feature when presented with the option.
Navigate to C:/Users/YOUR-NAME/AppData/Roaming/Electrum-zcl/wallets. Open the new standard wallet file with Notepad.
You will need to gather the 2 private keys and one public key. To find this easily, press “CTRL+F” and search for “xprv”. Copy the 2 “xprv” values as well as the last “xpub” value. You will need these in a later step.
Create a new “Multi-signature wallet”. Select “From 3 co-signers” on the first slider. Select “Require 2 signatures” on the second slider.
To add the first co-signer, click “Use public or private keys”. Enter the first xprv key in this box.
Add the second co-signer via a private key also.
Add the third co-signer with the public key. Complete the set-up.
Your wallet funds now have the ability to be sent from the multi-signature wallet.
Credit to @Entropyless and @daniel12 on Discord"

**Comment by ch4ot1c** [comment]
Glad everyone solved it. #44

**Comment by izzytoshi** [comment]
Awesome thank you so much that did it.  Although I'm thinking about the coinomy wallet as well.  They just announced ZCL as an addition to their tokens and they will also be supporting the fork.  Thanks again :)  Best of luck with all your trades.
