### ISSUE TITLE
Zclassic Electrum Wallet Will not connect to server

### ISSUE THREAD

**Issue by jvehovic** [z-classic/electrum-zcl#115]
I downloaded the zclassic electrum wallet and it will not connect to the server.  I sent zclassic from bittrex to my zclassic electrum wallet and it does not show the zclassic in my wallet however it does show on the zclassic block explorer.

**Comment by Astevens1976** [comment]
Mine worked just fine the first time I installed it yesterday

 

 

    Adam B. Stevens

     17574 Hardhat rd.

     STE 4

     Covington, La.  70435

     Phone: (985) 892-0555

     Fax: (985) 892-0095

**Comment by ghost** [comment]
I connected fine when i first downloaded it, yesterday tried to open and same issue cannot connect, any ideas

**Comment by jvehovic** [comment]
I turned off the proxy server this morning and it instantly connected.  I’m
in Cambodia traveling though so I’m not sure if that had something to do
with it or not.

**Comment by ghost** [comment]
already off, tried turning it on and still nothing

**Comment by MoritzNeto** [comment]
Was this solved? I'm having the same issue.

**Comment by NATURALCOIN** [comment]
I was having the same problem, but through research found a working server. My wallet is working fine now, no issues.

https://www.reddit.com/r/ZClassic/comments/87lbpo/zclassic_community_electrumx_servers_are_up_and/

**Comment by nimbosa** [comment]
this is a stale network connection issue and should be fixed by now.. please contact us via http://discord.gg/NRdczWC for further support if you need it, Thanks! @jvehovic @MoritzNeto
