### ISSUE TITLE
Can't send zcl out of the wallet

### ISSUE THREAD

**Issue by The-R4V3N** [z-classic/electrum-zcl#117]
Maybe I am to stupid but I can't send zcl to coinexchange or cryptopia. I use the latest windows  version with 2FA. Receive coins are no problem. I am not new to crypto so I know how to use a wallet. I just wonder if this has something to do with the 2FA? I

**Comment by The-R4V3N** [comment]
Found a solution.

**Comment by btvgeorge** [comment]
So you want to share how you fixed it?
