### ISSUE TITLE
Zclassic electrum wallet withdrawal error

### ISSUE THREAD

**Issue by juscrypto** [z-classic/electrum-zcl#124]
Hi! 

I tried to withdraw 13.23 ZCL from my wallet to an exchange but an error occurred . WHen I logged back into the account it shows the TX ID but theres no input / output after 3 hours + 

I would like to get my ZCL before the fork. I also checked the TX ID on the ZCL block explorer but nothing! Please I need help and I attached a screenshot.
![zclassicerrorshot](https://user-images.githubusercontent.com/36858028/36684276-315ce92a-1b63-11e8-83ca-cf6959979f1a.jpg)

**Comment by ch4ot1c** [comment]
http://zclassicexplorer.com/insight/address/t1Pt9VHPtD9nJiLQRniEPpEXsDyUm7v51Rn looks ok
