### ISSUE TITLE
1.0.3 vs 1.0.4

### ISSUE THREAD

**Issue by mjbrienza19** [z-classic/electrum-zcl#129]
Does it matter if I have the 1.0.3 version installed when the fork occurs? Am I still going to be able to claim Bitcoin private with the older version?

**Comment by Cryptoenail** [comment]
Did you find out the answer to this? I've been wondering/ concerned about the same thing. 

Also, if we do have to update, how do we ensure that our coins will transfer into the new update in time?

**Comment by lodotek** [comment]
no, it does not matter...

**Comment by sulmone** [comment]
1.0.4 uses newer servers that scale dynamically

**Comment by sulmone** [comment]
You can use either but 1.0.4 is preferred and will be more consistent
