### ISSUE TITLE
Cant make transaction 

### ISSUE THREAD

**Issue by Spilo26** [z-classic/electrum-zcl#139]
i am trying to send zcl grom wallet and an erroc accured ! "Server did not answer"! whats the problem ?

**Comment by Xentra-Team** [comment]
This wallet is useless

**Comment by ch4ot1c** [comment]
Sorry you're unhappy. We had nearly 20,000 concurrent users yesterday. I hope you've gotten connected - if not check the servers and try both:

<img width="502" alt="screenshot 2018-03-01 13 42 44" src="https://user-images.githubusercontent.com/2287825/36866627-6a2517ea-1d58-11e8-826d-f3e1a7d07faf.png">
