### ISSUE TITLE
Cant connect to server (1.0.3/4, Mac)

### ISSUE THREAD

**Issue by btvgeorge** [z-classic/electrum-zcl#144]
So I can't connect to the server and none of the easy solutions work. Does any one have an alternate server address they might be able to share?

**Comment by btvgeorge** [comment]
Downloaded 1.04  for mac and the wallet it still is not connecting

**Comment by btvgeorge** [comment]
says "error: server did not answer" when I try and send to an exchange

**Comment by btvgeorge** [comment]
unselected the "use proxy" check box and still does not work.

**Comment by btvgeorge** [comment]
Restarted computer and now the Electrum wallet just stays "synchronizing"

**Comment by btvgeorge** [comment]
and it's now disconnected....welp this sucks :(

**Comment by btvgeorge** [comment]
:Crickets:

**Comment by btvgeorge** [comment]
still having issues....anyone have any idea what sort of proxy settings i can  use or alternate server settings?

**Comment by ch4ot1c** [comment]
Try both servers in 1.0.4; they are up.
