### ISSUE TITLE
Electrum 1.04 disconnected

### ISSUE THREAD

**Issue by crypto10977** [z-classic/electrum-zcl#145]
Wallet is disco.  Upgraded from 1.02.  Wanted to get coins back on Bittrex, but no go?

**Comment by ch4ot1c** [comment]
Click the 'red dot' for disconnected, and try the other server.

<img width="502" alt="screenshot 2018-03-01 13 42 44" src="https://user-images.githubusercontent.com/2287825/36865901-716cd58a-1d56-11e8-909f-63b2f9641596.png">
