### ISSUE TITLE
ZCL sent to Cryptopia mia?

### ISSUE THREAD

**Issue by miyagison99** [z-classic/electrum-zcl#146]
green light said connected, sent out transaction, says 1137 confirmations, still not received......help me I beg of you

**Comment by ch4ot1c** [comment]
Hmm, the transaction certainly has occurred then. Where are you trying to receive it?

**Comment by miyagison99** [comment]
to cryptopia, still missing, they wont answer support ill just wait patiently? or can i send transaction data to someone approved to handle? what a mess :/

**Comment by ch4ot1c** [comment]
They are the processor of the transaction at this point. It will show up when they fully confirm it (up to them).
