### ISSUE TITLE
Strong password : cannot open encrypted wallet (imported)

### ISSUE THREAD

**Issue by DumaxFr** [z-classic/electrum-zcl#147]
When importing a wallet from private key
when encrypting wallet with a strong password (exceeds input box size)
Close the wallet after full sync
Open this encrypted wallet

Result when submitting password : Incorrect password

Expected : password should be correctly validated and wallet opened

**Comment by ch4ot1c** [comment]
Should work as expected. Clear the textbox / Check your password again.

**Comment by DumaxFr** [comment]
I repeated this procedure 3 or 4 times yesterday and wasn't working.
Now it's working as expected
