### ISSUE TITLE
Pressing the send button

### ISSUE THREAD

**Issue by JohnKerr12** [z-classic/electrum-zcl#151]
When pressing the send button on the 1.0.4 and 1.0.3 versions of the wallet nothing happens. It seems that only the "clear" button functions on this page.

**Comment by ch4ot1c** [comment]
Are you connected, green dot in the bottom right? No error?

**Comment by JohnKerr12** [comment]
Yes, everything is connected as expected. No error message is received.

**Comment by ch4ot1c** [comment]
What seed type did you import? Perhaps you made a watch-only wallet.

**Comment by JohnKerr12** [comment]
Think that might be the issue, there is no seed icon at the bottom right beside the rest of the icons. Will this mean I missed the snapshot too? Also, is there a way I can convert to a seed wallet?

Thanks for the help!

**Comment by ch4ot1c** [comment]
At setup time (File->New/Restore), import private keys, and type the keys - not the addresses. This will make a normal / spendable wallet.

**Comment by JohnKerr12** [comment]
Importing my private key crashes the wallet. Any ideas? No error is given.

**Comment by gmc513** [comment]
Yes it seems like I did the same thing. Will I be able to claim my BTCP?

**Comment by SanderMuller** [comment]
Do you still have the seed? Create a new wallet with the seed again in 1.0.4. 
I had the exact same issue. Could not send, and restoring from private keys crashed my wallet. Creating a new wallet in 1.0.4. with the seed worked though, I just managed to send my ZCL. 

AFAIK you should be able to claim your BTCP

**Comment by Protege89** [comment]
So I have the same problem with my zcl-electrum wallet.  Send button wont work. Created a new wallet with private key-wallet crashed.  Created another wallet with the seed- problem still there ( send button wont funtion).  Any other way to solve this problem ? Help is much appreciated

**Comment by Protege89** [comment]
PS. When i sent zcl to the wallet in the 1st place. It was in 1.0.0 zcl-electrum version. Already updated to 1.0.4 but still...

**Comment by Protege89** [comment]
Just tried to create another new wallet with seed and it works!.  Awesome
