### ISSUE TITLE
No Electrum-ZCL-Z_1.0.5-win.zip

### ISSUE THREAD

**Issue by ocarinaz64** [z-classic/electrum-zcl#167]
I don't see a new 1.0.5 win zip file included, even though the release says it should work with Windows.  And the Electrum_ZCL-Z_1.0.5-py3.6.egg isn't there, either.  Neither have anything listed under SHA256:

**Comment by jrkist** [comment]
im also having a similar problem! the zip that i download and unzip using winrar just puts files into a folder and thats it theres no program to run or a setup file or exec file??? i may be doing something wrong and would appreciate any help in this matter!

**Comment by ocarinaz64** [comment]
@jrkist - The zip files that are available aren't meant for Windows.  You probably didn't do anything wrong, it's just the right file isn't available.  Stick with 1.0.4 for now.

**Comment by nimbosa** [comment]
1.0.5 is a MacOS-only release, we now have the latest 1.0.6 for both MacOS and Windows:

https://github.com/z-classic/electrum-zcl/releases
