### ISSUE TITLE
How do I connect my electrum wallet?

### ISSUE THREAD

**Issue by hokiemike1** [z-classic/electrum-zcl#169]
I set up a Zclassic Electrum 1.0.4 wallet before the fork and have ZCL in it.  My wallet shows "not connected".  So how do I connect?   I'm trying to figure out how to receive my BTCP from the fork.

**Comment by ipince** [comment]
Same problem here.

My Zclassic Electrum (both 1.0.4 and 1.0.5) won't connect to the network.  I attempted all combinations of automatic vs. manual server selection and proxy vs. no proxy.

**Comment by tony-waters** [comment]
I'm having the same problem. I can see my ZCL, but its showing 'Not Connected'. Its a home computer and not behind a proxy. Have I left it too late to claim BTCP?

**Comment by ipince** [comment]
You should be able to claim BTCP:
1) download and install Electrum BTCP (from https://github.com/BTCPrivate/electrum-btcp/releases/)
2) open it, create a new wallet and choose "I have a seed", and use your ZCL wallet's seed.
3) you should see your BTCP and be able to move around.

For ZCL, however.. it's looking more complicated.  It seems the official ZCL servers have been shut down: "The Zclassic nodes will be shut down by the end of March."

https://medium.com/@ZclassicCoin/the-future-of-zclassic-c2b3206c1233

I'm trying to find alternative servers that will allow me to move my ZCLs, but have yet to find a working one...

**Comment by NATURALCOIN** [comment]
Same problem here, "Not connected." I read that article at medium.com (thanks ipince) and doesn't look good. Anyone have any servers that are working?

**Comment by ipince** [comment]
OK I was able to move my ZCLs:

1) download https://github.com/z-classic/zclassic-full-node-wallet/releases
2) import your private keys
3) wait like 4 hours for it download the entire network history (you might have to exit and restart the app)
4) your balance will appear. after this, I was able to send it to Bittrex and confirm that it arrived safe and sound.

Good luck!

**Comment by NATURALCOIN** [comment]
ipince,

How is it downloading the entire network history if all the ZCL servers are offline? Where is the full node wallet getting the information from?

Thanks

**Comment by NATURALCOIN** [comment]
ipince,

Nevermind, I found another link that contains a working ZCL server.

https://www.reddit.com/r/ZClassic/comments/87lbpo/zclassic_community_electrumx_servers_are_up_and/

**Comment by Andy198919** [comment]
The same issue, bought some ZCL recently, it was working but now no connection - NATURALCOIN, 50002 doesn't seem to give access? What to do? Have I lost my coins? This is crazy because Zclassic is listed on coinbase, is exchanged on changelly, etc. Is it a total scam now or something can be done?

**Comment by Andy198919** [comment]
Tools=>Network: under Server Tab, deselect "Select server automatically"

and enter electrum.zclassic.community , port is 50002  - seems to be the solution.

**Comment by NATURALCOIN** [comment]
It's not a scam at all. ZCL is just in a redevelopment phase I guess you could call it. I just checked my Electrum wallet 1.0.3 and its connected fine, no issues. I would check your firewall(s) to make sure nothing is blocked.

Second, to my knowledge, ZCL is not listed on coinbase. The only coins I see on it are BTC, BCH, ETH, and LTC.

**Comment by NATURALCOIN** [comment]
Just saw your post - sounds like you're all good.

**Comment by tony-waters** [comment]
I set the new server name to 'electrum.zclassic.community' - and it works - thanks for your help :)

**Comment by VictorLux** [comment]
Please go under tools/network
And put as in the attachment.
Stop & restart your wallet.
Let me know if issues.
You can join us on telegram : https://t.me/ZclassicCE
or Discord : https://discordapp.com/invite/NRdczWC

Vic. Zclassic Community Edition Team.
![capture d ecran 2018-04-29 a 18 01 18](https://user-images.githubusercontent.com/37399521/39408536-1d001b3c-4bd8-11e8-8f85-6f137ea78ba9.png)
