### ISSUE TITLE
Server did not answer???

### ISSUE THREAD

**Issue by jeffmessner** [z-classic/electrum-zcl#171]
I tried to transfer my Zcl balance to Bittrex and everytime I try it says 
1-Signing in transaction
2-Broadcasting transaction
3-Error: Servor did not answer

Anyone knows how I can fix this? It says: always use the latest version of electrum but it doesn't seem to be available for Pc yet. Thx

**Comment by jeffmessner** [comment]
In the bottom left corner it says Not connected. I don't understand what I have to do get my wallet connected.

**Comment by NATURALCOIN** [comment]
Had the same problem, did some research and found this first link which got me a little worried
https://medium.com/@ZclassicCoin/the-future-of-zclassic-c2b3206c1233

but then found this which contains a working ZCL server address. I just synced my wallet and got my ZCL.
https://www.reddit.com/r/ZClassic/comments/87lbpo/zclassic_community_electrumx_servers_are_up_and/

**Comment by jeffmessner** [comment]
Wow! Thank you very much!!!!
