### ISSUE TITLE
Server not Connecting

### ISSUE THREAD

**Issue by kellergoech** [z-classic/electrum-zcl#172]
I dont get a connection to the Server. I already tried using the other Serve by choosing the connection Server Manually. Also did i try to ping to the Server Location (this was successfull). Is there any other Server than the two (electrum.zclassic.org or zcl-electrum.com) which i can use? Or anything else i can do? It was working 2 Weeks ago with v1.0.3, i already did the Update to 1.0.4 still the same Problem.

greetings,
Kellergoech

**Comment by NATURALCOIN** [comment]
Hello,

Same problem here. The servers went offline. Take a look.

https://medium.com/@ZclassicCoin/the-future-of-zclassic-c2b3206c1233

**Comment by NATURALCOIN** [comment]
Just found another post that contained a working ZCL server and additional positive information.

https://www.reddit.com/r/ZClassic/comments/87lbpo/zclassic_community_electrumx_servers_are_up_and/

**Comment by kellergoech** [comment]
Nice, just tried it and its working. Thank you!
