### ISSUE TITLE
 plz help me zclassic wallet not connected 

### ISSUE THREAD

**Issue by omarrand** [z-classic/electrum-zcl#173]

**Comment by NATURALCOIN** [comment]
Omarrand,

Try this link. Worked for me. Manually enter the server name.

https://www.reddit.com/r/ZClassic/comments/87lbpo/zclassic_community_electrumx_servers_are_up_and/

**Comment by VictorLux** [comment]
Please go under tools/network
And put as in the attachment.
Stop & restart your wallet.
Let me know if issues.
You can join us on telegram : https://t.me/ZclassicCE
or Discord : https://discordapp.com/invite/NRdczWC

Vic. Zclassic Community Edition Team.
![capture d ecran 2018-04-29 a 18 01 18](https://user-images.githubusercontent.com/37399521/39408522-e24ce84e-4bd7-11e8-8321-c80ac00d1333.png)

**Comment by gitnewb1** [comment]
Hello, I am running win10 with wallet 1.0.4.  I have tried the above steps to update to the new server  over and over again but still get the red circle and no connection.  I have disabled the firewall.
Not sure if this port is used for TCP but a telnet to the server and port 50002 does not get anything back.
Can anyone help?

**Comment by NATURALCOIN** [comment]
That's strange. I just checked my wallet and no issues. I'm running Windows 7 with 1.0.3 though. However, I would suspect the OS version would not make a difference. Maybe your ISP's router/firewall is blocking something?

**Comment by gitnewb1** [comment]
I am trying to confirm if it is a networking issue, if you telnet to that server and port does it connect?

**Comment by NATURALCOIN** [comment]
I am unable to telnet as well, however that simply could mean they are not allowing it. Also, electrum.zclassic.community does not respond to ping requests, which again could simply be disabled on their side. Both not working are not necessarily indicative of a problem on their side.

**Comment by nimbosa** [comment]
this is a stale network connection issue and should be fixed by now..  please contact us via http://discord.gg/NRdczWC for further support if you need it, Thanks! @omarrand @gitnewb1
