### ISSUE TITLE
network connection

### ISSUE THREAD

**Issue by hwillso** [z-classic/electrum-zcl#174]
I have no net work connection can you help

**Comment by VictorLux** [comment]
Please go under tools/network
And put as in the attachment.
Stop & restart your wallet.
Let me know if issues.
You can join us on telegram : https://t.me/ZclassicCE
or Discord : https://discordapp.com/invite/NRdczWC

Vic. Zclassic Community Edition Team.
![capture d ecran 2018-04-29 a 18 01 18](https://user-images.githubusercontent.com/37399521/39408511-b55bd70a-4bd7-11e8-9581-1cf11ef5981e.png)

**Comment by NATURALCOIN** [comment]
Thank you Victor. I meant to respond last night. I have posted the same information in several other requests.

Are you with the new ZClassic Dev Team?

**Comment by VictorLux** [comment]
Hi,

I'm in the Zclassic Community Edition team, we planned to prepare a proposal to the BTCP team in order to continue development of ZCL.

Cheers,
Vic.

**Comment by tykwaan** [comment]
I tried this and it didnt work

**Comment by VictorLux** [comment]
did you check proxy tab on network ? unselect Proxy please.

**Comment by tykwaan** [comment]
Got It next question i have my wallet is saying my transaction is not verified what does that mean exactly?

**Comment by VictorLux** [comment]
you have to wait confirmations check your transaction using explorer : http://explorer.zclmine.pro/

**Comment by sp1200** [comment]
Hi,

can I change receiving adress?
I mined to another adress..

Is it possible to mine to that wallet?
Think I need a transparet adress? Isn't it ??

Greetz

**Comment by nimbosa** [comment]
this is a stale network connection issue and should be fixed by now.. please contact us via http://discord.gg/NRdczWC for further support if you need it, Thanks! @hwillso @tykwaan
