### ISSUE TITLE
Missing Update Link

### ISSUE THREAD

**Issue by rwharram16** [z-classic/electrum-zcl#176]
Where can I find the download link for the latest version of the Electrum ZCL wallet for windows?

Electrum-ZCL-Z_1.0.5-win.zip

I can only see the macosx.dmg version listed on github.

**Comment by newmzy** [comment]
yes it says "updated explorer links" and lists a windows version but no link

**Comment by thisjrodriguez** [comment]
you use 1.0.4 for win (https://github.com/z-classic/electrum-zcl/releases/download/Z!1.0.4/Electrum-ZCL-Z_1.0.4-win.zip)

you need connect new electrumx server,
https://medium.com/@zclassicblue/new-zclassic-electrum-servers-announced-d7f6ea6d848f

**Comment by nimbosa** [comment]
as previously stated here: https://github.com/z-classic/electrum-zcl/issues/167, 1.0.5 is a MacOS-only release,

we now have the latest 1.0.6 for both MacOS and Windows: https://github.com/z-classic/electrum-zcl/releases
