### ISSUE TITLE
Sent 50 zcl to wallet and its stuck on syncronizing. PLEASE HELP

### ISSUE THREAD

**Issue by Silentftw** [z-classic/electrum-zcl#177]
Connected to electrum.zclassic.community server. connected to 2 nodes. Blockchain size says -1.
I sent t50 zcl from bittrex and on bittrex side its sent and confirmed but without any confirmations. 

![connected nodes](https://user-images.githubusercontent.com/42855480/44889683-96391880-ac9c-11e8-8495-735e103949c8.PNG)
![capture1](https://user-images.githubusercontent.com/42855480/44889708-bec11280-ac9c-11e8-80ba-ba0dab6f62ba.PNG)
In my electrum wallet i see no coins no balance NOTHING received it just sits there and says synchronizing forever. Ive restarted the wallet multiple times.

**Comment by VictorLux** [comment]
Hi,

Sorry for late reply, do you still have the issue ?

**Comment by mexican1973** [comment]
Connect to duckdns electrum server.

**Comment by nimbosa** [comment]
this is a stale network connection issue and should be fixed by now.. please contact us via http://discord.gg/NRdczWC for further support if you need it, Thanks! @Silentftw
