### ISSUE TITLE
Problem with sending ZCL

### ISSUE THREAD

**Issue by cspek** [z-classic/electrum-zcl#181]
I use wallet !Z.1.0.3 on windows 7 or vista. I can't send zcl to other wallet because i got error: Server is not answer after 4 hours signing transaction. I have tried one time but after 3 hours signing transaction i just click exit this was waste of time. i Have imported wallet by private key because on mac Wallet not working. Why i can't send ZCL and everything operation is so long?

**Comment by nimbosa** [comment]
Hi @cspek,

What issues did you encounter with the Electrum Wallet on MacOS? Is it the same issues on Windows? Please reach one of our volunteers for support here: https://discord.gg/45NNrMJ.

Any additional information will help us resolve this.  Thanks!

**Comment by cspek** [comment]
On Mac i have !Z1.0.5 but wallet doesn't work, infinity sync. On Windows i have every transaction not veryfied, but i have correct status connected and balance. I have tried send my ZCL to other wallet and after 4 hours with Message "signing transaction" i give up because this was no sense, i have tried a few times but still nothing.

**Comment by cspek** [comment]
And i don't have correct blocks in network, blockchain have more block thank community

**Comment by VictorLux** [comment]
Hi,

Please do a backup and then please install and test the 1.0.6 Pre-Release for Mac.

Let me know if it works.

Vic.

**Comment by nimbosa** [comment]
This should be fixed by now @cspek. Please tell us if you have any updates. Thanks!
