### ISSUE TITLE
Missing .zip for windows

### ISSUE THREAD

**Issue by imclint21** [z-classic/electrum-zcl#182]
Hello guys,

I would like to download zcl electrum wallet for windows and apparently in the releases it does not appear, there are also an available issue on this, but apparently it's not fixed.

Can you add to the releases the windows binaries ?

Thanks

**Comment by VictorLux** [comment]
Hello,

Testing are on going on the latest windows version, should be in pre-release soon.

Cheers,
Vic.

**Comment by imclint21** [comment]
Yes okay

**Comment by nimbosa** [comment]
FIXED! 1.0.6 is NOT zipped (RAW .exe) but next releases from 1.0.7 onward will be..

https://github.com/z-classic/electrum-zcl/releases
