### ISSUE TITLE
Current USD Ammount Show BTC instead of ZCL

### ISSUE THREAD

**Issue by Fritzerton** [z-classic/electrum-zcl#23]
<img width="748" alt="screen shot 2018-01-20 at 9 08 03 am" src="https://user-images.githubusercontent.com/35083649/35184270-7a5b4f3c-fdc1-11e7-94b6-de5689e5d5af.png">

**Comment by Fritzerton** [comment]
This is on the Mac wallet

**Comment by sulmone** [comment]
This should be fixed in 1.0.3
