### ISSUE TITLE
Initial Roadmap of UI changes to support ZCL

### ISSUE THREAD

**Issue by ch4ot1c** [z-classic/electrum-zcl#3]
- ZCL instead of BTC for text **(Done)**
- Change 'Send' textbox named 'Description' to 'Label' or remove; Add 'Memo' fields
- Integrate (and remove) 'Preview' button into 'Send' button
- Make 'History' filterable by 'Memo?'
- Replace Electrum BTC app icon with ZCL logo **(Done)**

**Comment by ch4ot1c** [comment]
'satoshi' to 'zatoshi'

**Comment by sulmone** [comment]
We could start by stripping down to barebones and then building it back up as we get functionality as well

Start off by picking the electrum server you want to connect to and importing some private keys.

I liked the way you could select the address to send from in the desktop zclassic wallet.  Do you think it is easier to choose for them?

**Comment by ch4ot1c** [comment]
@csulmone agreed, mvp first. I think we should use a standard 'Electrum' approach to building outbound txns; maketx in lib/coinchooser.py lays this out. We can bubble up extra config to the user where appropriate when the time comes

Added 'Memos' to the GUI/UX project roadmap; closing this
