### ISSUE TITLE
Can't Reopen Wallet After Closing

### ISSUE THREAD

**Issue by Fritzerton** [z-classic/electrum-zcl#35]
Using the .dmg file on my Mac with High Sierra 10.13.2. I can mount and open the wallet fine but once I close the wallet I can't find the file anywhere to open the wallet again. The previous alpha release had a folder named "Electrum-ZCL" saved in Users/my_user that had the file to open the wallet. This folder is not saved there when using the dmg.

**Comment by Fritzerton** [comment]
Once Electrum is mounted, I can open a new finder window and drag electrum to applications folder and that solves the issue. This should be automated during install to make it easier for users.

**Comment by ch4ot1c** [comment]
We will continue to improve upon the installer. I always view my mounted drives from the Finder sidebar. For now, as you stated, drag the .app into the `Applications/` folder before using, and you should be all set. (You can then unmount/eject the .dmg)
