### ISSUE TITLE
Inputs from shielded addresses are not displayed as available balance

### ISSUE THREAD

**Issue by darthcrypto87** [z-classic/electrum-zcl#38]
I have 1 address holding my ZCL. There are 4 inputs that came from shielded addresses and only one input came from a public address.
The electrum wallet only shows the input that came from a public address. All others are not visible.

I did a transaction with the swing wallet of the whole balance to a public address and then transfered it back to my other address and only since then the whole balance is visible.

**Comment by ch4ot1c** [comment]
Shielded addresses on this wallet are a work in progress (not ready yet). Remember that your transactions live on the blockchain - so they will always be verifiable from a block explorer like zclassicexplorer.com. 

I will update this thread as soon as they're visible :) Thank you for opening the issue

**Comment by ch4ot1c** [comment]
Z->T Transactions should now be visible in your wallet, using our latest version: https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.3
