### ISSUE TITLE
Electrum Requests Bitcoin Mode When Using Hardware Device

### ISSUE THREAD

**Issue by Fritzerton** [z-classic/electrum-zcl#40]
Needs to be changed to request Zcash mode.
<img width="595" alt="screen shot 2018-01-25 at 5 25 05 pm" src="https://user-images.githubusercontent.com/35083649/35415942-6282a80a-01f5-11e8-8971-78ef87c416d4.png">

**Comment by coinman112** [comment]
Just a quick question, I accidentally sent zclassic to a zcash address on my trezor, I was wondering wether this electrum wallet being built by the great folk will support hardware integration. And if so would it be possible for me to recover the coins 
Regards
