### ISSUE TITLE
Electrum-ZCL-Z_1.0.0.exe has stopped working

### ISSUE THREAD

**Issue by rbasw-aculp** [z-classic/electrum-zcl#43]
![image](https://user-images.githubusercontent.com/20358292/35478824-482573de-03ad-11e8-936e-14e3ff53fb44.png)

Trying to open backup wallet from previous version crashes on Windows 10.

**Comment by theov3rc0mer** [comment]
Bug confirmed. Tried to import my wallet (importing from Eleos) and application crashed. I get the same error on windows and on linux, here is the exception taken from the linux terminal (archlinux)

`Traceback (most recent call last):
  File "/home/stefano/electrum-zcl-Z-0.1.0/gui/qt/installwizard.py", line 189, in on_filename
    self.storage = WalletStorage(path, manual_upgrades=True)
  File "/home/stefano/electrum-zcl-Z-0.1.0/lib/storage.py", line 72, in __init__
    self.raw = f.read()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 61: invalid continuation byte
Aborted (core dumped)`

**Comment by seriouslox** [comment]
Can confirm this too. Windows 7 Ultimate 64bit.

**Comment by mrtweed** [comment]
same issue for me. win 7 professional 64bit.

**Comment by josecostapinto** [comment]
I was able to import to set it up using the key from Eleos, however the balance was always 0. Restarted it and remain 0. I know it worked since the default address was the same I had in Eleos but couldn’t make it work. I set up a new one and transfer the fund from one wallet to another, it’s just 0.0001 zcl fee.

**Comment by creatormtr** [comment]
Whats a problem ? How  to open backup elios wallet ? 
![screenshot](https://user-images.githubusercontent.com/35892290/35482655-16a977d0-0441-11e8-8799-50e27cfb3c62.png)

**Comment by ch4ot1c** [comment]
So far, 'importing private keys' during wallet setup (and typing them in manually) has been the way I've been testing imports. Adding cross-wallet support will come, but please try this manual method.

**Comment by ch4ot1c** [comment]
(Update to the latest release; type in private keys at wallet setup time)
