### ISSUE TITLE
Electrum wallet issue : could not retrieve terms of service

### ISSUE THREAD

**Issue by VRLST** [z-classic/electrum-zcl#45]
Can anyone help with this? 

<img width="379" alt="screen shot 2018-01-27 at 8 50 05 pm" src="https://user-images.githubusercontent.com/35884819/35479117-da7beea2-03a3-11e8-83de-b2f9fd346aa7.png">

**Comment by YoungerT** [comment]
Also had this issue. Mac version 10.13.2

**Comment by ch4ot1c** [comment]
Please upgrade to the latest version: https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.2

If you were trying to make a 2FA wallet and are having other trouble, see #44.
