### ISSUE TITLE
wallet exe not compatible, I am using a 32-bit operating system windows 7

### ISSUE THREAD

**Issue by mulutub** [z-classic/electrum-zcl#48]
I got this message after running the electrum zcl-z 1.0.0.exe
X "The version of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher."
Just wanted to point out that I am currently using the Electrum wallet version 3.0.5 and ledger nano s without any issues.
Thanks

**Comment by GrannyCryptomaster** [comment]
It's only working with Windows x64bit. This should be specified on the download page. I tryed in Windows 7 x32bit too. Not working. In Windows 7 x64bit and 10 x64bit it's working.

**Comment by ch4ot1c** [comment]
Thank you for investigating; I will add this to the info
