### ISSUE TITLE
ZCL Electrum wallet no connection

### ISSUE THREAD

**Issue by astronyu** [z-classic/electrum-zcl#49]
Downloaded the new wallet and test receiving funds ok. But then it went offline i.e. showing no connection. Tried restarting the app to no avail.

At the time network showing none connected. Set server automatically was ticked. Only has zcl-electrum.com:50002 in the list

Platform: MacOS 10.13.3

**Comment by ch4ot1c** [comment]
Do you still have this issue with the latest release? https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.2

**Comment by astronyu** [comment]
It is seems now working fine. There are times when it disconnect and shows no connection. Still, a good progress, wallet still looking basic, hope to have more features in it soon.

**Comment by g-coxon** [comment]
Ok so downloaded the wallet and its working well, great work.
Transferred my ZCL over the this new Electrum Wallet
To check though for the BTCP snapshot it there a specific part of the wallet the the ZCL needs to be in or if it's just showing in the wallet balance that is fine to receive BTCP? Cheers.

**Comment by ch4ot1c** [comment]
@g-coxon Any T address will certainly be eligible (check the addresses section if you want specific addresses, and their corresponding private keys can be exported from the wallet too. And/or, just keep your seed words handy.)

**Comment by g-coxon** [comment]
@ch4ot1c Are T address literally just an address tat starts with a 't'?

**Comment by astronyu** [comment]
@ch4ot1c Seems I still have issues with the wallet. It looks like it does synchronized but I'm not receiving the coin I sent to my address.

This is the transaction that I made from mining.
http://explorer.zclmine.pro/address/t1fVfghBHc2cEVhz25NaH8fnNQUxwmAjcL6
Tx http://explorer.zclmine.pro/tx/e848f88f66122b70edcdf028dbf04fd6f777c00418138c310b48e9ffc78d5861

But electrum wallet did not show such transaction.
