### ISSUE TITLE
Could not retrieve terms of service

### ISSUE THREAD

**Issue by praveenparimi** [z-classic/electrum-zcl#51]
While completing installation i get the following error meesage

Could not retrieve Terms of Service:
Could not find a suitable TLS CA certificate bundle, invalid path: /private/var/folders/vy/b840561s2cd1x14rnv62w65m0000gn/T/AppTranslocation/F782A4CB-5123-41AB-9F7A-3393FAB29204/d/Electrum.app/Contents/Resources/lib/python36.zip/certifi/cacert.pem

**Comment by bharath9d** [comment]
Receiving the same issue for Mac.

**Comment by praveenparimi** [comment]
I just cleared all of the installed zcl and this time didn't select 2FA, clicked just Next, and got the installation complete. However, the status on the bottom left saying 'Not Connected'

**Comment by JFRD** [comment]
I've got exactly the same problems with sierra high

**Comment by yanivcohenita** [comment]
same here... mac ...

**Comment by ch4ot1c** [comment]
1) Record all seeds + private keys you've generated (to a text file, secured to your standards):
 'Export private keys' (titlebar) & 'View seed words' (statusbar at the bottom right)

2) Make a complete backup of your electrum profile, just incase:
`mkdir ~/e-zcl-backup && cp -R ~/.electrum-zcl ~/e-zcl-backup`

3) Download the latest version: https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.1

4) **Double check that your files all copied from the backup**, and then delete ~/.electrum-zcl/

5) Use Standard Wallet for your setup. This wallet type will send and receive funds you provide via T addresses.

Your patience is appreciated and we're doing our best. I will update this thread when we have new information.

**Comment by fuzzytechie** [comment]
Got same issue for iOS

**Comment by ch4ot1c** [comment]
This is an old issue from 1.0.0; should be fixed
