### ISSUE TITLE
Checking transactions while Syncing crashes wallet

### ISSUE THREAD

**Issue by RabidP0tat0** [z-classic/electrum-zcl#53]
Wallet seems to be stuck at Syncing phase.  Noticed that a couple transactions looked incomplete.  Tried to double click on to see details and wallet crashes to desktop.

![capture](https://user-images.githubusercontent.com/35899159/35485406-54b9f4b4-042d-11e8-8e1e-5ef1bebff558.JPG)
![capture2](https://user-images.githubusercontent.com/35899159/35485418-773d8fc8-042d-11e8-93ed-5a08e70687ca.JPG)

**Comment by ch4ot1c** [comment]
Please try 1.0.3 - https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.3

**Comment by nimbosa** [comment]
this is an old bug and should be fixed in newer releases now: https://github.com/z-classic/electrum-zcl/releases

please contact us via http://discord.gg/NRdczWC for further support if you need it, Thanks!
