### ISSUE TITLE
Mac wallet - Showing 0 after transferring 99 coins from Private address in Swing Wallet

### ISSUE THREAD

**Issue by devsrini** [z-classic/electrum-zcl#54]
Hello, 
I have transferred some coins from Swing wallet (Private and Transparent addresses). All the transactions from transparent addresses are showing in correctly but the one sent from private address is not showing any amount in electrum wallet. Please help. 

Thanks

**Comment by ch4ot1c** [comment]
Private (Z) addresses a 'coming soon' feature in our Electrum client. Hold onto your private keys and seed words; that's all you'll need when the time comes.

Sorry for any inconvenience. Make a full backup of your wallet files and stay posted

**Comment by devsrini** [comment]
Thank you. Appreciate it.

**Comment by ch4ot1c** [comment]
Please try again with our latest release: https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.3

You should be able to view your transactions that were Z->T

Let us know how it goes!

**Comment by devsrini** [comment]
Awesome. It's working fine now. I can see my transactions. Appreciate your support. Closing the thread
