### ISSUE TITLE
Tx from Private key is a 'coming feature' ? Now my ZCL is in NO wallet.

### ISSUE THREAD

**Issue by dStorm-x58** [z-classic/electrum-zcl#57]
Please instruct how to retrieve ZCL back into a wallet.  Sent ZCL from swing wallet private address to zcl-electrum 2fa wallet that now says Tx = 1, funds = 0.0.  Yes, I would have taken everyone's word that zclassic swing wallet would be fine, though it was implied this is the one being supported directly.

**Comment by ch4ot1c** [comment]
Please see #44. Let me know if it works for you

**Comment by dStorm-x58** [comment]
Thanks for the reply. Just to clarify, I sent funds to the new zcl-electrum 2fa Windows wallet from a zclassic Windows swing wallet Private address, Should I still try to complete with these instructions or wait for support for private addresses?

**Comment by dStorm-x58** [comment]
Oh, woops, ch4ot1c is you. heh.

**Comment by ch4ot1c** [comment]
You can move your T funds around as you like. Currently you can only send them to other T addresses from our Electrum client. Z -> T transactions are coming within the next few weeks, but that's for sending **from** Electrum. Double check your funds after you get in the wallet via the retrieval steps.

**Comment by dStorm-x58** [comment]
I completed the following: I created a new standard / no pass wallet using the same seed as 2fa.  I extracted the pub and private keys from that result, and created a new multi-sig wallet.  This new multi-sig wallet pulled in the same values as the 2fa wallet, with the same results for the missing 4.1 ZCL.   That 4.1 ZCL was sent from the Private address of my zclassic swing wallet.  The provided pic was taken at two seperate times,  so it looks like I had 2fa and multi-sig open at same time but I didn't.

![capture](https://user-images.githubusercontent.com/15656733/35598310-820de992-05d7-11e8-8fea-818b837938c2.JPG)

**Comment by ch4ot1c** [comment]
Ok - today when consulting with our senior developer I determined that, in fact, those T->Z txns just won't show up until some specifics are implemented. This is one of our current tasks and I promise to let you know when we have a ready release for it.

Your transaction exists remember, as the block explorer says - so keep the seed for the wallet/addresses where you received, and you should be all set when the time comes.

**Comment by dStorm-x58** [comment]
Cool.  I'll keep all my keys, and thank you for the update.

**Comment by ch4ot1c** [comment]
https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.3
@dStorm-x58 
Please try this build - it now supports T->Z txns. Let me know if everything becomes visible.

Thank you

**Comment by dStorm-x58** [comment]
It worked!  Thank you very much.  And for the other user that was in the same boat, you mentioned v1.0.3 supports T->Z txns, and this resolved my Z->T txn.  So I guess it fixed all txns between public and private keys. Thank you again.

**Comment by ch4ot1c** [comment]
You're welcome
