### ISSUE TITLE
Shortcut Icon Failed on Windows

### ISSUE THREAD

**Issue by CryptoSinbad** [z-classic/electrum-zcl#62]
Got on my PC this morning ( I run windows) Shortcut to my ZClassic wallet failed. It asked to remove the shortcut from taskbar. So I did. Took about 15 min to find any ZClassic files on my PC. Once found the file for the Wallet, it also did not work. The notification is as follows:

Line:1
Char:5
Error: 'Document' is undefined
Code: 800A1391
Source: Microsoft JScript runtime error

I don't code, so I have no idea what happened here.

**Comment by CryptoSinbad** [comment]
Re-downloaded, and now it works. Idk what happened. Might still want to check it out tho

**Comment by ch4ot1c** [comment]
Perhaps you mixed up Eleos and Electrum?

**Comment by CryptoSinbad** [comment]
I think what might have happened was I didn't download/save the original file the first time I ran the program. After I re-downloaded everything I madebsure to save, and now it all seems to work

**Comment by ch4ot1c** [comment]
Ah - good catch. Thanks for noting it :)
