### ISSUE TITLE
Wallet Not sending ZCL

### ISSUE THREAD

**Issue by Rynok87** [z-classic/electrum-zcl#65]
HI,

When trying to send ZCL i am pressing preview or send and nothing is happening.

V1.0.2

Help would be appreciated, thanks!

**Comment by ronstoppable87** [comment]
Hi,

https://github.com/BTCP-community/electrum-zcl/issues/44

there are instructions below on how to fix it, it worked for me

**Comment by ch4ot1c** [comment]
Excellent 👍
