### ISSUE TITLE
Error: Could not retrieve Terms of Service

### ISSUE THREAD

**Issue by samtheloanman** [z-classic/electrum-zcl#69]
I am on a mac pro with version 10.13.3 High Sierra

I am receiving an error when trying to create my default wallet. The error message is below:
Could not retrieve Terms of Service:
Could not find a suitable TLS CA certificate bundle, invalid path: /Applications/Electrum.app/Contents/Resources/lib/python36.zip/certifi/cacert.pem

The file that is mentions "cacert.pem" is located at /Applications/Electrum.app/Contents/Resources/cacert.pem

Please correct path for this file.

**Comment by ch4ot1c** [comment]
Try this new release: https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.3
