### ISSUE TITLE
Update lib/checkpoints.json for ZCL

### ISSUE THREAD

**Issue by ch4ot1c** [z-classic/electrum-zcl#7]
It currently still contains the values for BTC

**Comment by nxsofsys** [comment]
Do we need checkpoints at all?

**Comment by Mrwh0** [comment]
im cheking that

**Comment by Mrwh0** [comment]
https://github.com/z-classic/zclassic/blob/master/src/chainparams.cpp#L129
last checkpoint stone write block 160000 & dec max target as parent_Id
        "000000065093005a1a46ee95d6d66c2b07008220ca64dd3b3a93bbd1945480c0",
 14134776517815698497336078495404605830980533548759267698564454644503805952

improve resources. as our headers bin is bigger
