### ISSUE TITLE
Change URLs in your fork

### ISSUE THREAD

**Issue by bauerj** [z-classic/electrum-zcl#70]
Hey,

we would appreciate if you could direct your users to your own bug tracker and your own website.

See spesmilo/electrum#4018, spesmilo/electrum#3852, spesmilo/electrum#3843, spesmilo/electrum#3840, spesmilo/electrum#3828, spesmilo/electrum#3815, spesmilo/electrum#3809 and spesmilo/electrum#3808.

You probably missed the following lines while changing the branding:

https://github.com/BTCP-community/electrum-zcl/blob/master/gui/qt/main_window.py#L519

https://github.com/BTCP-community/electrum-zcl/blob/master/gui/qt/main_window.py#L521

and especially:

https://github.com/BTCP-community/electrum-zcl/blob/master/gui/qt/main_window.py#L545

Thanks!

**Comment by ch4ot1c** [comment]
Thank you & Sorry 😃

**Comment by bauerj** [comment]
No worries. When are you going to release a new version with this merged?

**Comment by ch4ot1c** [comment]
Aiming for today

**Comment by nimbosa** [comment]
Fixed by: https://github.com/z-classic/electrum-zcl/pull/72 and subsequent changes.
