### ISSUE TITLE
SHA-256 for Electrum-ZCL-Z_1.0.3-win.exe does not match.

### ISSUE THREAD

**Issue by akcook** [z-classic/electrum-zcl#74]
SHA-256 for .exe is 982A5817A43B7AB3D7F5F5815DBB9CA1EAD70A2740973D4BB6E409248DF85F47

it should be 855eac62978c66d6f3d5f81f8679e7fdbe932e4128aa83770898d0e916b29cff

**Comment by Haikk** [comment]
I think this sha for zip file not for exe.

**Comment by tocorobo** [comment]
I second Haikk's comment; the SHA256 hash displayed on https://github.com/BTCP-community/electrum-zcl/releases of Electrum-ZCL-Z_1.0.3-win.zip is listed as:
SHA256: 855eac62978c66d6f3d5f81f8679e7fdbe932e4128aa83770898d0e916b29cff

I just downloaded that zip file and calculated its hash with powershell; it checks out for me just fine:

$(get-filehash .\Electrum-ZCL-Z_1.0.3-win.zip -algorithm sha256).hash
855EAC62978C66D6F3D5F81F8679E7FDBE932E4128AA83770898D0E916B29CFF

**Comment by sulmone** [comment]
The hash is for the zip file, correct.
