### ISSUE TITLE
zcl electrum z!1.0.2 not sending amount.

### ISSUE THREAD

**Issue by mrpvcs** [z-classic/electrum-zcl#75]
Hello
Team Electrum zcl

This morning I sent 0.07 zcl to cryptopia and never sent, I tried the second time, nothing and the third time it error messaged. Please help and thank you for your time on this matter.

**Comment by mgattueu** [comment]
Hi Team,

having same issue, no response clicking SEND button after filling all details. Please help.

Thanks

**Comment by ch4ot1c** [comment]
This is probably because you aren't getting successfully connected and syncd to zcl-electrum.com.

Try again real quick, and then if no luck, get the latest version: https://github.com/BTCP-community/electrum-zcl/releases/tag/Z!1.0.3

Let us know how it goes.

**Comment by mrpvcs** [comment]
Hello
Mgattueu and Jon Layton

Thank you for the quick reply, yes the wallet was not synced. All transfers
went through at some point. As well I think zcl explorer was down that
day.  I am very happy with the zcl wallet electrum over all.
