### ISSUE TITLE
Z!1.0.3 Keeps reconnecting and syncing, no balance shows

### ISSUE THREAD

**Issue by Rickou812** [z-classic/electrum-zcl#76]
Just installed Electrum Z!1.0.3 and seems to have issues connecting.  Install went smoothly.  Connects for about 10 seconds and the disconnects.  Doesn't seem to be syncing.  I sent some zcl to it, but it never showed in wallet.  The transaction is completed per block explorer. 

I have opened and closed the wallet a few times and is showing connected, but still not displaying balance.  How can I tell when/if it has synced?

**Comment by Rickou812** [comment]
My issue seemed to resolve itself.  opened wallet today, and funds are now displayed.
I noted on other posts, people noted the Sync status, however, in version 1.0.3 I see no such notification.  Can this be added back?  I have to assume in my case, although the light had turned green, the wallet wasn't 100% synced.

**Comment by awllc** [comment]
Is your wallet syncing automatically or do you have to do something to initiate syncing? Mine never syncs.

**Comment by sulmone** [comment]
We fixed some settings on the server yesterday.  Make sure you are on the 1.0.3 release and let it run for 5-10 minutes to sync and get caught up.  If that is still not working, close the application and delete the %APPDATA%\Electrum-zcl\blockchain_headers file. (this will not delete your private keys - it is from the public blockchain)  After it is deleted, restart the application and wait a few minutes for the application to download the file again and resync.
