### ISSUE TITLE
Can't ping zcl-electrum.com; Not syncing at all.

### ISSUE THREAD

**Issue by Haikk** [z-classic/electrum-zcl#77]
Wallet not syncing, Tried everything, also copied from another pc AppData>Electrum-zcl and still.

**Comment by wadragracer** [comment]
Haikk,  i'm having the same issue.
zcl-electrum.com Node has been stuck on block height 259318 it's been stuck for multiple hours. is your block height at that block?

**Comment by awllc** [comment]
Mine isn't connecting to the server at all. For the network host, only zcl-electrum.com is available, but it never connects.

**Comment by sulmone** [comment]
We fixed some settings on the server yesterday.  Make sure you are on the 1.0.3 release and let it run for 5-10 minutes to sync and get caught up.  If that is still not working, close the application and delete the %APPDATA%\Electrum-zcl\blockchain_headers file. (this will not delete your private keys - it is from the public blockchain)  After it is deleted, restart the application and wait a few minutes for the application to download the file again and resync.

**Comment by awllc** [comment]
I tried this and it is still red an hour later.

In the config file it has:  "server": "zcl-electrum.com:50002:s",

and that is the only server and port that is available once in the wallet. Might that be the problem?

**Comment by sulmone** [comment]
That is our main prod server.  One other possible workaround is to close the application, replace the %APPDATA%\Electrum-zcl\blockchain_headers file with this one: http://headers.zcl-electrum.com/blockchain_headers and restart electrum.  It sometimes takes a minute to connect and sync and then it should be fine.

**Comment by awllc** [comment]
Thanks for your help, but still not working. I may be better off hoping for support for the fork on Cryptopia and just leaving it there.

**Comment by sulmone** [comment]
Can you post a screenshot of your network window?  It should show which server you are trying / are connected to along with block height information.

I won’t give up until we find a solution!

**Comment by awllc** [comment]
![image](https://user-images.githubusercontent.com/29823558/35892840-1177dd30-0b60-11e8-9f4a-de204d74d786.png)

And 
![image](https://user-images.githubusercontent.com/29823558/35892856-2009e690-0b60-11e8-8b34-7f1b1f04cd63.png)

**Comment by sulmone** [comment]
Can you try unchecking "Select server automatically" and using 104.154.244.167 as the server?

Thanks!

**Comment by awllc** [comment]
![image](https://user-images.githubusercontent.com/29823558/35894013-89cebf24-0b65-11e8-9371-ebcfc264a26c.png)
As you can see, I've put it in, but it doesn't reflect in the list of available hosts below.

**Comment by sulmone** [comment]
Hit the close button and it will attempt to connect again.  I am monitoring for connection errors in the server log now.

**Comment by awllc** [comment]
done

**Comment by sulmone** [comment]
How did you set up your wallet?  Could you try creating a new one with all default options?  I am seeing some errors around the wallet type.

**Comment by awllc** [comment]
I took all the defaults. The first time I wanted to give it a different name, but then it wouldn't open it when I came back the next day. So I deleted the folder and re-created it with all default options.

**Comment by awllc** [comment]
I just deleted everything and downloaded the zip again, then installed with all defaults. Do you want me to use 104.154.244.167 again or just leave it at the automatic connection default?

Also, if I use the paper wallet on your site, how would I access it to send out of the wallet or verify transactions? I don't see where there is any seed phrase, just the public and private keys for that one.

**Comment by sulmone** [comment]
There is a separate option to import the raw private key there

**Comment by sulmone** [comment]
If you start cmd and type 'ping zcl-electrum.com' do you get a response?

**Comment by awllc** [comment]
I get:

C:\Users\I>ping zcl-electrum.com

Pinging zcl-electrum.com [104.154.244.167] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 104.154.244.167:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),


I'm going offline for the night now.

**Comment by sulmone** [comment]
That is strange - it looks like you cannot connect to our google hosted compute server.  Are you on a restricted internet connection with a firewall?

**Comment by awllc** [comment]
No, just my regular old household cable internet connection to a laptop through ethernet.

**Comment by pettinesssss** [comment]
Tried everything too
Pinging zcl-electrum.com [104.154.244.167] with 32 bytes of data:
Reply from 104.154.244.167: bytes=32 time=295ms TTL=51
Reply from 104.154.244.167: bytes=32 time=291ms TTL=51
Reply from 104.154.244.167: bytes=32 time=286ms TTL=51
Reply from 104.154.244.167: bytes=32 time=292ms TTL=51

Ping statistics for 104.154.244.167:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 286ms, Maximum = 295ms, Average = 291ms

Not syncing

**Comment by pettinesssss** [comment]
![qqhh20180207220501](https://user-images.githubusercontent.com/36233274/35920529-1418c04c-0c53-11e8-828b-00b1ad18c398.png)
![qq207220538](https://user-images.githubusercontent.com/36233274/35920580-2f192904-0c53-11e8-8fb6-06bbb2566813.png)

**Comment by pettinesssss** [comment]
I deleted all the files and created a new one .
It works.
Thanks

**Comment by ch4ot1c** [comment]
Glad that updating your release version worked for you, @pettinesssss 

@awllc, I will keep this issue open so we can continue exploring your connection issues.

I know this sounds like a dumb request but bear with me - please restart your computer, router, and modem, and try again. Also look around in https://support.microsoft.com/en-us/help/4028544/windows-turn-windows-firewall-on-or-off, and see if you have any restrictions (particularly on port 50002). 

👍

**Comment by awllc** [comment]
I have Windows Defender firewalls turned off. I've decided to leave the ZCL on the exchange.

**Comment by Goldchatter** [comment]
Solution was given by csulmone earlier!

For me, only the following action required: Can you try unchecking "Select server automatically" (!)
Forget using 104.154.244.167 as the server. This is not needed for synchronisation to start, shortly after unchecking the box.

Thanks!

**Comment by ourlink** [comment]
I've tried all the given solutions too... I can ping the server just fine (See below). I have closed and reopened the application several times and still no connection.

I went back and deleted the blockchain_headers again and I'm in the process of trying to download those again.

**Comment by ourlink** [comment]
Pinging zcl-electrum.com [104.154.244.167] with 32 bytes of data:
Reply from 104.154.244.167: bytes=32 time=97ms TTL=58
Reply from 104.154.244.167: bytes=32 time=95ms TTL=58
Reply from 104.154.244.167: bytes=32 time=103ms TTL=58
Reply from 104.154.244.167: bytes=32 time=104ms TTL=58

Ping statistics for 104.154.244.167:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 95ms, Maximum = 104ms, Average = 99ms

**Comment by amirn44** [comment]
i have ping from zcl-electrum.com but not connected !! can help me?

**Comment by markseaberg** [comment]
Can someone please explain to me how I input another server other than zcl-electrum.com? When I first set up my account I imported my private keys into the wallet. Do I need to make a new zcl wallet and use the standard default option? Any help would be greatly appreciated.

**Comment by markseaberg** [comment]
Problem Solved. Make sure you uncheck the "Use Proxy" box when configuring your settings and it should connect to the zcl-electrum.com server

**Comment by Juan-Zcl** [comment]
Hi.

Here with the same problem.

My wallet used to work fine.  I had problems with my primary harddrive so I had to use another hardisk to re-install windows and all aplications including Electrum-ZCL-Z_1.0.3.

I'm not sure if it connected at that moment but what I know is at this moment it can't syncromize anymore.

I did all what you said in this post, but nothig works.  I installed with a new one wallet (doesn't work) inserting the seed of my original wallet (doesn't work).  and at this moment I don´t know what to do;  Please can you help me.

I'm copying captures of my wallet (the one with my original wallet seed) but they are the same other people paste.

Regards.

![image](https://user-images.githubusercontent.com/38634452/39099714-f9f4161a-464c-11e8-9316-7191769ad429.png)
![image](https://user-images.githubusercontent.com/38634452/39099724-1c6ca2ca-464d-11e8-87e5-d352e0f49e16.png)
![image](https://user-images.githubusercontent.com/38634452/39099731-340a2dbc-464d-11e8-9037-78922ddb7a8d.png)
![image](https://user-images.githubusercontent.com/38634452/39099741-487b6932-464d-11e8-98b7-8069d82b50b8.png)

**Comment by NATURALCOIN** [comment]
Hello - I had the same problem, but found a working server. Here is the link. Under server uncheck "Select server automatically" and use the one mentioned in the link. The original/default ZCL server is gone from I can see based on the article in the second link.

I am syncing fine now. No issue.

https://www.reddit.com/r/ZClassic/comments/87lbpo/zclassic_community_electrumx_servers_are_up_and/

https://medium.com/@ZclassicCoin/the-future-of-zclassic-c2b3206c1233

**Comment by Juan-Zcl** [comment]
Hi.  NATURALCOIN.

yes, you're right.  I changed the server and everything is ok.  My coins came back. (only $0.50 but it's the begining).

Thank you very much.

**Comment by nimbosa** [comment]
Thanks @NATURALCOIN!

**Comment by nimbosa** [comment]
fixed by https://github.com/z-classic/electrum-zcl/pull/178 as of Sep 14, 2018 in https://github.com/z-classic/electrum-zcl/tree/Z!1.0.6
