### ISSUE TITLE
ZCL Electrum ver. 1.0.3 - wrong wallet address

### ISSUE THREAD

**Issue by GrannyCryptomaster** [z-classic/electrum-zcl#78]
I first installed 1.0.2 and made my first wallet. I received payments in it. Today I installed 1.0.3 and my receiving address changed. I deleted the wallet file and made a new wallet with the old seed from the first wallet. My initial receiving address appeared and the transactions synced. I restarted my computer after a while, and when I opened Electrum 1.0.3, again my initial receiving address changed. WTF? It changes the receiving address with each restart? Do i need to recreat the wallet each time? Now the sync dosen't work either. Man, you have many bugs to address.

**Comment by GrannyCryptomaster** [comment]
Nevermined. I discovered the setting: Transactions > use change addresses. After deselecting the option, my receiving address dosen't change anymore.

**Comment by ch4ot1c** [comment]
Ok :). Change addresses can be useful - re-using addresses makes you easier to de-anonymize - but everything certainly can work with them disabled.
