### ISSUE TITLE
ZCL Electrum 1.0.3 on Windows 10 Pro 64-bit - how to luanch the program?

### ISSUE THREAD

**Issue by tester2011** [z-classic/electrum-zcl#81]
Hi Guys,

This will hopefully be a simple one...

I d/l and installed the latest version of the wallet (1.0.3) on my Windows 10 Pro 64-bit system. All went fine, set up wallet, got seed, etc. Looks cool. Seems much quicker to use than the Swing-based wallet. All good...

However, when I shut down the wallet and came back to my PC a few minutes later, I can't find any desktop/start-menu icon for the ZCL Electrum wallet.

Same deal when looking in the Program Files and Program Files (x86) folders on the PC - no sign of the Electrum wallet.

I do find some files in the C:\Users\xxxxx\AppData\Roaming\ folder - there's an "Electrum-zcl" folder, which contains three sub-folders: "wallets", "certs" and "forks") and four files: "blockchain_headers", "recent_servers", "daemon" and "config".

So how the heck to a start the wallet program? Where are the executables and other program files?

Cheers,

Mike.

**Comment by Goldchatter** [comment]
Mike, I thought I was the only one. Same problem here.

Can someone explain to us how we can execute the wallet program after closing?

**Comment by ch4ot1c** [comment]
It should be a standalone. Check your Downloads, or in the folder where you unzipped it.

You're free to place it anywhere, including just the Desktop. The path for your data directory (wallets and such) will always be the same; it will know to look there.

**Comment by Goldchatter** [comment]
I think you are missing our problem. 
Indeed the wallet is standalone, but the wallet folder contents do not contain a program exe file to (re)start the wallet program window. We are talking AFTER full installation from Downloads folder. Like a pictogram exe for starting the wallet again after closing it. 

Any other ideas / solutions?

**Comment by tester2011** [comment]
When I execute the Electrum-ZCL-Z_1.0.3-win.exe file, it (after about 10-20 seconds of disk access on my PC) displays a window titled "Zclassic Electrum - Install Wizard" - this is EVERY time I run it, not just the initial run. It doesn't seem to install any application files. However, when I first ran it it lead me through the various steps/options to set up my wallet. Each successive run (after the 10-20 second delay), it simply prompts for the password for the wallet I originally created and all seems fine. 

The Electrum-ZCL-Z_1.0.3-win.zip download is 204MB, most other Electrum builds are only around 12MB - why the huge difference in size? I'm guessing it installs the 'blockchain_headers' file as mentioned in my original post.

The issue is that if it is a whopping great 204MB standalone app, why is it so huge, why is it called "Install Wizard" and what the heck is it doing for 20 seconds before the program, window appears? :-)

I know it's a fairly new project, but there also seems to be a distinct lack of Zclassic-specific documentation.

Cheers,

Mike.

**Comment by tburkgitter** [comment]
I have the same problem.  I'm using Windows 7N OS.  I have to install the wallet each time I want to use the wallet.  For this reason, I wonder if it installed correctly?

**Comment by ghost** [comment]
Yep, I was stumbled so I just unzipped the exe file to my desktop, ran it and just asked for my password.  And I see my balance now.

**Comment by tester2011** [comment]
I'm unable to unzip the .exe file - I get a messages saying "Cannot open file as archive" (7-Zip).

How did you do it?

**Comment by nimbosa** [comment]
this is a stale issue, but just for reference
- the program's profile data folder is located at: `%AppData%\Electrum-ZCL\` in Windows,
- while the executable file is located wherever you chose to download / unzip it, make sure your download is complete, and
- a good 7-zip unarchiver is [PeaZip](http://www.peazip.org/) to extract it
