### ISSUE TITLE
unable to send or preview with 2Fa wallet

### ISSUE THREAD

**Issue by uroojkamran** [z-classic/electrum-zcl#98]
hi there, i downloaded zclassic electrum for windows and created 2fa wallet, didn‘t realize that you guys mentioned not to use it. I was able to deposit ZCL into my zclassic electrum wallet. Now when i try to withdraw by going into send tab and when i try to click on send or preview, nothing happens. the password dialog should appear when i click on send but it does not. please fix

**Comment by ch4ot1c** [comment]
Please see https://github.com/BTCP-community/electrum-zcl/issues/44

**Comment by uroojkamran** [comment]
Thanks a million, this worked :)

Sent using the mail.com mail app
